// Provides synthetic survey-quality data for the first TakwimuCheck product shell.

import type { DemoProject, RuleCoverageItem, ValidationIssue } from '@/types/validation';

export const demoProject: DemoProject = {
  id: 'demo-household-survey',
  name: 'Household Wellbeing Survey',
  datasetLabel: 'household_wave_01.csv',
  source: 'Synthetic demonstration dataset',
  lastRunLabel: 'Demonstration run completed today',
  metrics: {
    recordsChecked: 506,
    rulesExecuted: 14,
    errors: 19,
    warnings: 31,
    reviewedIssues: 12,
    openIssues: 38,
  },
  validationCoverage: 96,
  metadataCoverage: 88,
};

export const ruleCoverage: RuleCoverageItem[] = [
  {
    id: 'required-fields',
    label: 'Required fields',
    coverage: 100,
    checksExecuted: 4,
    status: 'attention',
  },
  {
    id: 'type-range',
    label: 'Type and range checks',
    coverage: 98,
    checksExecuted: 4,
    status: 'attention',
  },
  {
    id: 'skip-logic',
    label: 'Skip logic',
    coverage: 94,
    checksExecuted: 2,
    status: 'attention',
  },
  {
    id: 'consistency',
    label: 'Cross-variable consistency',
    coverage: 92,
    checksExecuted: 2,
    status: 'attention',
  },
  {
    id: 'duplicates',
    label: 'Duplicate detection',
    coverage: 100,
    checksExecuted: 2,
    status: 'passed',
  },
];

export const demoIssues: ValidationIssue[] = [
  {
    id: 'ISS-001',
    ruleId: 'REQ-RESPONDENT-ID',
    title: 'Missing respondent identifier',
    message: 'A required respondent identifier is blank, preventing reliable record tracing.',
    severity: 'error',
    status: 'open',
    recordId: 'ROW-0142',
    variable: 'respondent_id',
    observedValue: 'Blank',
    expected: 'A non-empty unique identifier',
    category: 'Required field',
  },
  {
    id: 'ISS-002',
    ruleId: 'RANGE-AGE',
    title: 'Age outside approved range',
    message: 'The recorded age is greater than the maximum allowed by the survey metadata.',
    severity: 'error',
    status: 'open',
    recordId: 'HH-0087',
    variable: 'respondent_age',
    observedValue: '147',
    expected: '18 to 110 years',
    category: 'Range check',
  },
  {
    id: 'ISS-003',
    ruleId: 'SKIP-PREGNANCY',
    title: 'Skip instruction not followed',
    message: 'A pregnancy follow-up response exists where the eligibility condition was not met.',
    severity: 'error',
    status: 'reviewed',
    recordId: 'HH-0114',
    variable: 'pregnancy_follow_up',
    observedValue: 'Yes',
    expected: 'Blank when eligibility condition is false',
    category: 'Skip logic',
  },
  {
    id: 'ISS-004',
    ruleId: 'CONSIST-RESIDENCE-AGE',
    title: 'Residence duration exceeds age',
    message: 'Years lived in the community are greater than the respondent age.',
    severity: 'warning',
    status: 'open',
    recordId: 'HH-0189',
    variable: 'years_in_community',
    observedValue: '52 years; age 43 years',
    expected: 'Residence duration less than or equal to age',
    category: 'Consistency',
  },
  {
    id: 'ISS-005',
    ruleId: 'CODE-WATER-SOURCE',
    title: 'Unrecognised response code',
    message: 'The water-source value is not listed in the approved metadata code set.',
    severity: 'warning',
    status: 'deferred',
    recordId: 'HH-0240',
    variable: 'water_source',
    observedValue: '97',
    expected: 'One of the approved codes 1 to 8',
    category: 'Code check',
  },
  {
    id: 'ISS-006',
    ruleId: 'DUP-HOUSEHOLD',
    title: 'Possible duplicate household',
    message: 'Two records share the same location, household head and telephone fragment.',
    severity: 'warning',
    status: 'reviewed',
    recordId: 'HH-0311 / HH-0312',
    variable: 'household_identity',
    observedValue: 'High similarity match',
    expected: 'One distinct record per household',
    category: 'Duplicate detection',
  },
];

export const workflowSteps = ['Upload', 'Validate', 'Review', 'Report'] as const;
